package view;

public enum Menu {

    PATIENTS_MENU, APPOINTMENTS_MENU, PRESCRIPTIONS_MENU,
    ADD_PATIENT_RECORD, UPDATE_PATIENT_RECORD, VIEW_PATIENT_RECORD, DELETE_PATIENT_RECORD,
    ADD_APPOINTMENT, UPDATE_APPOINTMENT, VIEW_APPOINTMENT, DELETE_APPOINTMENT,
    ADD_PRESCRIPTION, UPDATE_PRESCRIPTION, VIEW_PRESCRIPTION, DELETE_PRESCRIPTION;

}
